eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
spring:
  redis:
    host: localhost
    port: 6379
  #3.JPA
  jpa:
    database: MySQL
    show-sql: false
    open-in-view: false

logging:
  level:
    root: warn
#    root: debug