version: '3'

services:
  ihrm_system:
    image: ihrm_system
    build: ./ihrm_system
    ports:
      - 9004:9004
    environment:
      - spring.profiles.active=prod
  ihrm_social_securitys:
    image: ihrm_social_securitys
    build: ./ihrm_social_securitys
    ports:
      - 9005:9005
    environment:
      - spring.profiles.active=prod




