version: '3'

services:
  ihrm-attendance:
    image: ihrm-attendance
    build: ./ihrm_attendance
    ports:
      - 9006:9006
    environment:
      - spring.profiles.active=prod

  ihrm-audit:
    image: ihrm-audit
    build: ./ihrm_audit
    ports:
      - 9009:9009
    environment:
      - spring.profiles.active=prod




