version: '3'

services:
  mysql:
    image: ihrm-mysql:latest
    build: ./mysql
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=123456
  redis:
    image: redis:latest
    ports:
    - 6375:6375



