version: '3'

services:
  ihrm-eureka:
    image: ihrm-eureka
    build: ./ihrm_eureka
    ports:
      - "6868:6868"
    environment:
      - spring.profiles.active=prod
    hostname: ihrm-eureka

  ihrm-gate:
    image: ihrm-gate
    build: ./ihrm_gate
    ports:
      - "9001:9001"
    environment:
      - spring.profiles.active=prod
    depends_on:
      - ihrm-eureka
    hostname: ihrm-gate

  ihrm-system:
    image: ihrm-system
    build: ./ihrm_system
    ports:
      - 9004:9004
    environment:
      - spring.profiles.active=prod



