eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.15.251.224:3306/ihrm?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
  #3.JPA
  jpa:
    database: MySQL
    show-sql: false
    open-in-view: false
  #3.JPA
  jpa:
    database: MySQL
    show-sql: false
    open-in-view: false

logging:
  level:
    root: warn
#    root: debug