eureka:
  client:
    service-url:
      defaultZone: http://ihrm_eureka:6868/eureka
spring:
  datasource:
    act:
      jdbc-url: jdbc:mysql://mysql:3306/act?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    ihrm:
      jdbc-url: jdbc:mysql://mysql:3306/ihrm?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  redis:
    host: redis
    port: 6379

